### ISSUE TITLE
CCFG Corruption

### ISSUE THREAD

**Issue by eujean** [openthread/ot-cc13x2-cc26x2#24]
**Describe the bug** 
Occassionally a device will lose its config entirely. It seems that the CCFG is partially overwritten when this happens. It seems to occur when a device loses power, or starts up. This makes the device get stuck in an endless reset loop, since for example at address 0x50004fb4, which is the MODE_CONF of the ccfg, the clock information is specified which gets overwritten.

For example, when reading this register, I would get 0x31ffbbf3, but when this happens, reading this same address I would get 0xffffffff, which causes the switching of the oscillator to fail and therefore reset.

In a few rare cases, the debug port has also been locked.

**To Reproduce** 

1. [2653602db5cf27fbcb0bac5ead759513c5d7361f](https://github.com/openthread/ot-cc13x2-cc26x2/commit/2653602db5cf27fbcb0bac5ead759513c5d7361f)
2. CC2652
3. ./script/build -DTI_PLATFORM=cc2652

**Expected behavior** 
CCFG should not be overwritten by application

**Additional context** 
At first I thought it might be a flash problem, and looking at the flash driver [(here)](https://github.com/openthread/ot-cc13x2-cc26x2/blob/main/src/cc2652/flash.c#L49), the value 0x18 doesn't seem right. But that didn't resolve the issue.

I then tried to protect the whole sector using driverlib as follows:
`FlashProtectionSet(0x50003000, FLASH_WRITE_PROTECT);`

but this also didn't seem to make a difference.

Any other thoughts or suggestions?

**Comment by srickardti** [comment]
Hey Eujean,

Looks like the issue was a mis-understanding of what the `otPlatFlashErase` function meant. Looks like it was trying to erase all the flash storage area, when it was supposed to erase only one of the swap sections.

So, when the higher flash swap section was erased, it would also take out the flash page containing the CCFG.

You have to commit the change to the flash protection to write it to the CCFG with `FlashProtectionSave`
